name: CI

on: [push]

jobs:
  test_php:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        php: [8.0]
    name: PHP-${{ matrix.php }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Cache PHP dependencies
        uses: actions/cache@v2
        with:
          path: vendor
          key: ${{ runner.OS }}-build-${{ hashFiles('**/composer.lock') }}

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          extensions: dom, curl, libxml, mbstring, zip, pcntl, pdo, sqlite, pdo_sqlite, bcmath, soap, intl, gd, exif, iconv
          coverage: none

      - name: Install PHP dependencies
        run: composer install -q --no-ansi --no-interaction --no-scripts --no-suggest --no-progress --dev

      - name: Lint/Analyze PHP
        run: composer test